name: Check PR Title
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.26.1
          run_install: true
      - name: Check PR Title against Commitlint
        run: |
          echo "${{ github.event.pull_request.title }}" > pr-title.txt
          MY_FILE=pr-title.txt npx commitlint --env MY_FILE

